name: Bot de tareas del piso

on:
  schedule:
    - cron: '0 18 * * 0'   # UTC 18:00 = España 20:00 (ojo con la zona horaria)
  workflow_dispatch:       # permite lanzarlo manualmente

jobs:
  send-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run bot
        env:
          EMAIL: ${{ secrets.EMAIL_USER }}
          PASSWORD: ${{ secrets.EMAIL_PASS }}
        run: python tareas_piso.py
